FROM node:23.5.0-alpine

WORKDIR /app


COPY build_output/standalone /app
COPY build_output/static /app/.next/static
COPY public /app/public


ENV HOSTNAME 0.0.0.0
ENV PORT 443
EXPOSE 443

CMD ["node", "server.js"]
