############################################################
#  [*] PortforwarderUpdater — the layer4 TCP forward renderer
#
#  Renders the whole portforwarder Caddyfile from the
#  backend's port forward table and hot-reloads the
#  hosting-users-portforwarder container. One layer4 listener
#  per forward: :<public port> proxying straight to the VM's
#  address at hosting-users-dind-<id>:<internal port> — plain
#  TCP passthrough, no TLS and no HTTP awareness. With no
#  forwards the file is just the banner (no layer4 block), so
#  a reload closes every listener.
#
#  The compose file publishes the 30000-30029 pool on the
#  container; a listener outside that range would render fine
#  but never receive traffic — the backend's validation is
#  what keeps the table inside the pool.
#
#  The rendered file is the throwaway artifact — the forward
#  table is the source of truth, and every mutation rewrites
#  the file wholesale.
############################################################

import os
import re
from subprocess import Popen, PIPE








############################################################
# PortforwarderUpdater
############################################################
#
# The template strings live as class attributes, written
# indented for readability and dedented once at class-build
# time (the re.sub below each) — the same shape as the
# users-Caddy CaddyfileUpdater.
#
# Methods:
#   generate_caddyfile — forward rows → the whole file text
#   save_caddyfile     — write to PORTFORWARDER_CADDYFILE_LOCATION
#   reload_portforwarder — docker exec caddy reload
############################################################

class PortforwarderUpdater:


    # Banner block — also the whole file when no forwards exist
    generated_file_banner = '''
    ########################################################################################################################
    ##############      This configuration file is automatically generated by the hosting-control-docker      ##############
    ##############  Any changes to this file will be lost when the system initiates a configuration reload.   ##############
    ########################################################################################################################
    '''
    generated_file_banner = re.sub(r'^ {4}', '', generated_file_banner, flags=re.MULTILINE)






    ############################################################
    # generate_caddyfile
    ############################################################
    #
    # port_forwards → the complete Caddyfile text. Each entry
    # is a dict with lowercase keys (the backend's wire shape):
    # id, virtualserverid, publicport, internalport. All three
    # numbers pass through int() — the ports and the VM id are
    # spliced into config text, so a non-integer must blow up
    # here instead of becoming a config injection.
    #
    # The layer4 app lives in the Caddyfile global options
    # block; with zero forwards the block is omitted entirely
    # (an empty config is valid, an empty layer4 app is not).
    #
    # Used by:
    #   - portforwarder/routes.updateportforwarderconfig_HTTPPOST
    ############################################################

    def generate_caddyfile(self, port_forwards):

        # Start building the Caddyfile content.
        caddyfile_content = ""
        caddyfile_content += self.generated_file_banner + "\n"

        # No forwards — the banner alone is the whole (valid)
        # config, and reloading it closes every listener
        if len(port_forwards) == 0:
            return caddyfile_content

        # Open the global options block with the layer4 app.
        caddyfile_content += "{\n"
        caddyfile_content += "    layer4 {\n"

        # Iterate over all port forward entries.
        for port_forward in port_forwards:
            forward_id = int(port_forward["id"])
            virtual_server_id = int(port_forward["virtualserverid"])
            public_port = int(port_forward["publicport"])
            internal_port = int(port_forward["internalport"])

            # One listener per forward — a raw TCP proxy into
            # the VM's address on the filtered-users network
            caddyfile_content += "\n"
            caddyfile_content += f"        # Port forward ID: {forward_id}\n"
            caddyfile_content += f"        :{public_port} {{\n"
            caddyfile_content += "            route {\n"
            caddyfile_content += f"                proxy hosting-users-dind-{virtual_server_id}:{internal_port}\n"
            caddyfile_content += "            }\n"
            caddyfile_content += "        }\n"

        # Close the layer4 app and the global options block.
        caddyfile_content += "\n"
        caddyfile_content += "    }\n"
        caddyfile_content += "}\n"

        return caddyfile_content






    ############################################################
    # save_caddyfile
    ############################################################
    #
    # Write the rendered file to the shared portforwarder
    # volume (PORTFORWARDER_CADDYFILE_LOCATION, default
    # /users-portforwarder/Caddyfile).
    #
    # Used by:
    #   - portforwarder/routes.updateportforwarderconfig_HTTPPOST
    ############################################################

    def save_caddyfile(self, caddyfile_content):
        caddy_location = os.environ.get("PORTFORWARDER_CADDYFILE_LOCATION", '/users-portforwarder/Caddyfile')
        with open(caddy_location, "w") as file:
            file.write(caddyfile_content)






    ############################################################
    # reload_portforwarder
    ############################################################
    #
    # `caddy reload` inside the portforwarder container,
    # through the docker socket. Returns True/False — a failed
    # reload leaves the OLD listeners serving (Caddy keeps
    # running), and the route answers 500 so the backend rolls
    # the forward change back.
    #
    # Used by:
    #   - portforwarder/routes.updateportforwarderconfig_HTTPPOST
    ############################################################

    def reload_portforwarder(self):
        process = Popen([
            'docker', 'exec', 'hosting-users-portforwarder', 'caddy', 'reload', '--config', '/etc/caddy/Caddyfile'
        ])
        output, error = process.communicate()

        return process.returncode == 0
