############################################################
#  [*] CaddyfileUpdater — the users-Caddy vhost generator
#
#  Renders the whole users Caddyfile from the backend's
#  domain table and hot-reloads the users Caddy container.
#  One server block per domain: https with a real cert when
#  ssl=1, plain http otherwise; Cloudflare-only domains get
#  `tls internal` plus an IP allowlist that 403s anything not
#  arriving through Cloudflare. Everything proxies to the
#  VM's inner Caddy at hosting-users-dind-<id>:80, with a
#  502 handler for VMs that host nothing on port 80. A
#  catch-all :80 block answers for every unknown domain.
#
#  The rendered file is the throwaway artifact — the domain
#  table is the source of truth, and every mutation rewrites
#  the file wholesale.
############################################################

import os
import re
from subprocess import Popen, PIPE








############################################################
# CaddyfileUpdater
############################################################
#
# The template strings live as class attributes, written
# indented for readability and dedented once at class-build
# time (the re.sub below each). cloudflare_block is the one
# WITHOUT a dedent on purpose: it is spliced INSIDE server
# blocks, so it keeps its extra indentation.
#
# Methods:
#   generate_caddyfile — domain rows → the whole file text
#   save_caddyfile     — write to CADDYFILE_LOCATION
#   reload_caddy       — docker exec caddy reload
############################################################

class CaddyfileUpdater:


    # Global options block
    global_options = '''
    ########################################################################################################################
    ##############      This configuration file is automatically generated by the hosting-control-docker      ##############
    ##############  Any changes to this file will be lost when the system initiates a configuration reload.   ##############
    ########################################################################################################################

    {
        # Global options block
        log {
            output file /var/log/caddy/access.log {
                roll_size 100mb
                roll_keep 5
                roll_keep_for 720h
            }
            format json
        }
    }
    '''
    global_options = re.sub(r'^ {4}', '', global_options, flags=re.MULTILINE)


    # Cloudflare snippet (shared configuration)
    cloudflare_snippet = '''
    # Saltinis: https://www.cloudflare.com/ips/
    (cloudflare) {
        remote_ip 103.21.244.0/22
        remote_ip 103.22.200.0/22
        remote_ip 103.31.4.0/22
        remote_ip 104.16.0.0/13
        remote_ip 104.24.0.0/14
        remote_ip 108.162.192.0/18
        remote_ip 131.0.72.0/22
        remote_ip 141.101.64.0/18
        remote_ip 162.158.0.0/15
        remote_ip 172.64.0.0/13
        remote_ip 173.245.48.0/20
        remote_ip 188.114.96.0/20
        remote_ip 190.93.240.0/20
        remote_ip 197.234.240.0/22
        remote_ip 198.41.128.0/17
    }
    '''
    cloudflare_snippet = re.sub(r'^ {4}', '', cloudflare_snippet, flags=re.MULTILINE)


    # Blocks every request that did not arrive through a
    # Cloudflare IP — spliced inside a server block, hence no
    # dedent
    cloudflare_block = '''
        # Block Non cloudflare requests
        @block_non_cloudflare {
            not {
                import cloudflare
            }
        }
        respond @block_non_cloudflare "Sorry for disapointing you, but this service is only accessible through Cloudflare" 403
    '''


    # The catch-all for every domain the table does not know
    resolve_any_other_domain_names = '''
    :80 {
        respond "Hosting platform does not host any applications at this domain name." 200
    }
    '''
    resolve_any_other_domain_names = re.sub(r'^ {4}', '', resolve_any_other_domain_names, flags=re.MULTILINE)






    ############################################################
    # generate_caddyfile
    ############################################################
    #
    # dns_entries → the complete Caddyfile text. Each entry is
    # a dict with lowercase keys (the backend's wire shape):
    # id, virtualserverid, domainname, iscloudflare (0/1),
    # ssl (0/1). The old docstring documented CSV-era
    # capitalized keys that the code never reads — the "CSV"
    # wording in the comments below is the same fossil.
    #
    # Used by:
    #   - main.updatecaddyconfig_HTTPPOST — every regeneration
    ############################################################

    def generate_caddyfile(self, dns_entries):

        # Start building the Caddyfile content.
        caddyfile_content = ""
        caddyfile_content += self.global_options + "\n\n"
        caddyfile_content += self.cloudflare_snippet + "\n\n"
        caddyfile_content += "\n"

        # Iterate over all DNS entries.
        for dns_entry in dns_entries:
            dns_id = dns_entry["id"]
            virtual_server_id = dns_entry["virtualserverid"]
            domain_name = dns_entry["domainname"]
            is_cloudflare = dns_entry["iscloudflare"]
            is_ssl = dns_entry["ssl"]


            # Begin the server block — https only when ssl=1
            server_block = f"# DNS ID: {dns_id}\n"
            if is_ssl == 1:
                server_block += f"{domain_name} {{\n"
            else:
                server_block += f"http://{domain_name} {{\n"


            # TLS: Cloudflare terminates public TLS itself, so
            # its domains get an internal cert; plain ssl=1
            # domains get a real ACME cert
            if is_cloudflare == 1:
                server_block += "    tls internal"
            else:
                if is_ssl == 1:
                    server_block += "    tls admin@knf.vu.lt"
            server_block += "\n\n"


            # If the server should only be accessible through Cloudflare, add the block.
            if is_cloudflare == 1:
                server_block += self.cloudflare_block
                server_block += "\n\n"


            # Reverse proxy into the VM's inner Caddy; behind
            # Cloudflare the real client IP arrives in the
            # forwarded header, otherwise it IS the peer
            if is_cloudflare == 1:
                server_block += f"    reverse_proxy http://hosting-users-dind-{virtual_server_id}:80 {{\n"
                server_block += "        header_up X-Forwarded-For {http.request.header.X-Forwarded-For}\n"
                server_block += "    }\n"
            else:
                server_block += f"    reverse_proxy http://hosting-users-dind-{virtual_server_id}:80 {{\n"
                server_block += "        header_up X-Forwarded-For {remote_host}\n"
                server_block += "    }\n"

            # Add default response if upstream server could not be connected
            server_block += f"    handle_errors 502 {{\n"
            server_block += "        respond \"Virtual server does not host any app on port 80 or the app cannot be accessed externally.\" 502\n"
            server_block += "    }\n"
            server_block += "}"

            # Add a newline to separate the server blocks.
            server_block += "\n\n\n\n"

            # Add the server block to the caddyfile content.
            caddyfile_content += server_block

        # Add the resolve any other domain names block.
        caddyfile_content += self.resolve_any_other_domain_names + "\n\n"

        return caddyfile_content






    ############################################################
    # save_caddyfile
    ############################################################
    #
    # Write the rendered file to the shared users-caddy volume
    # (CADDYFILE_LOCATION, default /users-caddy/Caddyfile).
    #
    # Used by:
    #   - main.updatecaddyconfig_HTTPPOST
    ############################################################

    def save_caddyfile(self, caddyfile_content):
        caddy_location = os.environ.get("CADDYFILE_LOCATION", '/users-caddy/Caddyfile')
        with open(caddy_location, "w") as file:
            file.write(caddyfile_content)






    ############################################################
    # reload_caddy
    ############################################################
    #
    # `caddy reload` inside the users Caddy container, through
    # the docker socket. Returns True/False — a failed reload
    # leaves the OLD config serving (Caddy keeps running), and
    # the route answers 500 so the backend rolls the domain
    # change back.
    #
    # Used by:
    #   - caddy/routes.updatecaddyconfig_HTTPPOST
    ############################################################

    def reload_caddy(self):
        process = Popen([
            'docker', 'exec', 'hosting-users-caddy', 'caddy', 'reload', '--config', '/etc/caddy/Caddyfile'
        ])
        output, error = process.communicate()

        return process.returncode == 0
