services:

  sistema-endpoint:
    container_name: sistema-endpoint
    image: nginx:alpine-slim
    read_only: false
    volumes:
      - ./endpoint/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 10080:80
    networks:
      - external
      - isolated
    restart: unless-stopped


  sistema-dockge:
    container_name: sistema-dockge
    image: louislam/dockge:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dockge/data:/app/data
      - /apps/aplikacijos:/apps/aplikacijos
    environment:
      - DOCKGE_STACKS_DIR=/apps/aplikacijos
    networks:
      - isolated
    restart: unless-stopped


  sistema-filebrowser:
    container_name: sistema-filebrowser
    image: sistema-filebrowser
    build:
      context: ./filebrowser
      dockerfile: Dockerfile
    read_only: false
    volumes:
      - /apps/aplikacijos:/data
    networks:
      - isolated
    restart: unless-stopped


  sistema-webssh2:
    container_name: sistema-webssh2
    image: billchurch/webssh2:0.4.6
    networks:
      - external
    restart: unless-stopped



networks:
  external:
    external: true
  isolated:
    name: sistema-isolated
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 172.18.1.0/24
          gateway: 172.18.1.1
